name: 'Jira Fields as PR Labels'
author: 'Maurice Williams'
description: "Add labels to a pull request based on certain fields from Jira"
inputs:
  github-token:
    description: 'Token used to add labels to the PR. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  jira-api-token:
    description: "API Token used to access the Jira REST API. Must have read access to your Jira projects & issues. For details, see Atlassian's official documentation: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/"
    required: true
  jira-username:
    description: "Username that can use the Jira API token. Must have read access to your Jira projects & issues. For details, see Atlassian's official documentation: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/"
    required: true
  jira-base-url:
    description: 'Your Jira subdomain. i.e.: https://your-domain.atlassian.net'
    required: true
  issue-key-location:
    description: 'Where in the PR to look for issue key. Values can be: `branch`, `title` or `both`'
    default: title
    required: false
  sync-issue-type:
    description: 'Flag indicating if the "issue type" from Jira should be added as a PR label'
    default: true
    required: false
  sync-issue-priority:
    description: 'Flag indicating if the "priority" value from Jira should be added as a PR label'
    default: true
    required: false
  sync-issue-labels:
    description: 'Flag indicating if the "labels" from Jira should be added as a PR label'
    default: true
    required: false
  ticket-regex:
    required: false
    description: 'To link a PR with a jira ticket, PR title and body will be scanned using this regex'
    default: '([A-Z]+[A-Z0-9_]*-\d+)'
  label-prefix:
    required: false
    description: 'Prefix used when adding labels to the PR.'
outputs:
  issue-key:
    description: 'The issue key that was found'
  issue-type:
    description: 'The Jira issue type for the corresponding Jira issue'
  issue-priority:
    description: 'The priority set in Jira for the corresponding Jira issue'
  issue-fix-version:
    description: 'The fix version on the corresponding Jira issue'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'refresh-cw'
  color: 'blue'
