name: 'GitHub Label + Jira'
author: 'Maurice Williams'
description: 'Apply's a label in GitHub to match the Jira issue type'
inputs:
  github-token:
    description: 'Token used to update PR description and add labels. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  jira-api-token:
    description: "API Token used to access the Jira REST API. Must have read access to your Jira projects & issues. For details, see Atlassian's official documentation: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/"
    required: true
  jira-username:
    description: "Username that can use the API token. Must have read access to your Jira projects & issues. For details, see Atlassian's official documentation: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/"
    required: true
  jira-base-url:
    description: 'The subdomain of JIRA cloud that you use to access it. Ex: "https://your-domain.atlassian.net"'
    required: true
  issue-key-location:
    description: 'Where to look for issue key: branch | title | both'
    default: title
    required: false
outputs:
  issue-key: 
    description: 'The issue key that was found'
  issue-type: 
    description: 'The issue type found in Jira'
  issue-priority: 
    description: 'The priority set on the matching jira issue'
  issue-fix-version: 
    description: 'The fix version on the matching jira issue'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'refresh-cw'
  color: 'blue'
