name: Test this action

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Do the thing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set PR label
        uses: ./
        id: myAction
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}

      - name: Get the output issue key
        run: echo "${{ steps.myAction.outputs.issue-key }}"

      - name: Get the output issue type
        run: echo "${{ steps.myAction.outputs.issue-type }}"

      - name: Get the output issue priority
        run: echo "${{ steps.myAction.outputs.issue-priority }}"

      - name: Get the output issue fix version
        run: echo "${{ steps.myAction.outputs.issue-fix-version }}"
        